name: flashcardsapp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.6
  intl: ^0.17.0  # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/biology.png
    - assets/images/science.png
    - assets/images/lucidlog.png
    - assets/images/background.jpg
    - assets/images/julian2.jpg
    - assets/images/addbutton.png
    - assets/images/cloud.png




  fonts:
    - family: Ckhans
      fonts:
        - asset: assets/fonts/Ckhans Fonts - Buckin Bold Demo.otf
          weight: 400
    - family: Ckhans2
      fonts:
        - asset: assets/fonts/ITC Benguiat Gothic Heavy Oblique.otf
          weight: 400      
